### PR TITLE
Sphinx JS

### PR DESCRIPTION
**Pull request by mythmon**
Based on #3. First relevant commit is d2da723.

### CODE REVIEW

**Comment by mythmon** [comment]
@erikrose Hey, we're using sphinx-js! Could you give commit d2da723 a quick once-over, to see if I did anything weird?

**Comment by rehandalal** [comment]
Not sure why https://github.com/mozilla/pioneer-studies-addon-utils/pull/4/commits/7c27d391edcdbbd1ed6f37061f45030064e090d1 is lingering and also this has a conflict

**Comment by mythmon** [comment]
I don't expect this PR will update automatically. I'll need to rebase it manually.

**Comment by mythmon** [comment]
Rebased.

**Comment by erikrose** [comment]
@mythmon Added a few comments about features that might make your life easier. Thanks for letting me know you're using sphinx-js! :-D

**Pull request merged**
